// Website planning, launch checks, and automation estimates | TypeScript
"use client";
import { useState } from "react";
import { Workspace, Field, Choice, Result, Notice } from "./ToolUI";
import { downloadText } from "@/lib/browser-files";

export function WebsiteBrief() {
  const [business, setBusiness] = useState(""); const [audience, setAudience] = useState(""); const [goal, setGoal] = useState(""); const [pages, setPages] = useState("Home, Services, About, Contact"); const [features, setFeatures] = useState(""); const [timeline, setTimeline] = useState("Flexible"); const [budget, setBudget] = useState("To discuss"); const [notes, setNotes] = useState(""); const [notice, setNotice] = useState("");
  const brief = business.trim() ? `WEBSITE PROJECT BRIEF\n\nBusiness: ${business}\nAudience: ${audience || "To discuss"}\nMain goal: ${goal || "To discuss"}\nPages: ${pages}\nFeatures: ${features || "To discuss"}\nTimeline: ${timeline}\nBudget: ${budget}\n\nAdditional notes\n${notes || "None yet"}` : "";
  return <Workspace slug="website-brief" help="This brief is a starting point, not a quote. Download it freely. To discuss it with NSheth, copy the brief, open their website, and paste or attach it when you choose to contact them."><div className="grid md:grid-cols-2 gap-5"><Field label="Business name (required)" value={business} onChange={setBusiness} /><Field label="Who is the website for?" value={audience} onChange={setAudience} /><Field label="What should visitors do?" value={goal} onChange={setGoal} placeholder="Book a call, buy products, request a quote..." /><Field label="Pages you need" value={pages} onChange={setPages} /><Field label="Features and integrations" value={features} onChange={setFeatures} multiline /><Field label="Additional notes" value={notes} onChange={setNotes} multiline /><Choice label="Timeline" value={timeline} onChange={setTimeline} options={[["Flexible","Flexible"],["Within a month","Within a month"],["1–3 months","1–3 months"],["3+ months","3+ months"]]} /><Field label="Budget range and currency (optional)" value={budget} onChange={setBudget} /></div><Result text={brief} filename="website-project-brief.txt" /><button className="btn btn-secondary" disabled={!brief} onClick={async () => { try { await navigator.clipboard.writeText(brief); setNotice("Brief copied. Use the NSheth link below to start a conversation and paste it when ready."); } catch { setNotice("Download the brief above, then attach it when contacting NSheth."); } }}>Prepare brief for NSheth</button><Notice>{notice}</Notice></Workspace>;
}

const checks = [
  ["Content", "State what you offer and who it is for", "Use a clear primary contact or purchase action", "Replace sample text and verify contact details", "Use real project examples and approved testimonials"],
  ["Experience", "Test navigation and forms on a small phone", "Check keyboard access, labels, and visible focus", "Add descriptive image alternatives", "Compress images and test loading on mobile data"],
  ["Launch", "Check titles, descriptions, and social previews", "Confirm your domain, HTTPS, and canonical URLs", "Check broken links and the 404 page", "Verify enquiry delivery with a real test submission"],
  ["After launch", "Submit the sitemap to Search Console", "Document your update and backup process", "Review enquiries and fix recurring friction", "Check analytics settings against your privacy information"],
];
export function WebsiteChecklist() {
  const [done, setDone] = useState<string[]>([]); const [notice, setNotice] = useState(""); const total = checks.reduce((n,g) => n+g.length-1,0);
  const save = () => { try { localStorage.setItem("nytm-launch-checklist", JSON.stringify(done)); setNotice("Progress saved on this device. Use Load saved progress when you return."); } catch { setNotice("Storage unavailable. Export your checklist instead."); } };
  return <Workspace slug="website-checklist" help="This is a manual checklist, not an automated website audit. Only checked item identifiers are saved when you choose Save progress."><div className="flex flex-wrap items-center gap-3"><strong>{done.length} / {total} complete</strong><progress className="flex-1 min-w-32" max={total} value={done.length} aria-label="Launch checklist progress" /></div><div className="grid md:grid-cols-2 gap-8">{checks.map(([group,...items],g) => <section key={group}><h2 className="text-lg font-semibold mb-4">{group}</h2><div className="space-y-4">{items.map((item,i) => { const id=`${g}-${i}`; return <label key={id} className="flex items-start gap-3 text-sm"><input type="checkbox" checked={done.includes(id)} onChange={e => setDone(e.target.checked ? [...done,id] : done.filter(x=>x!==id))} /><span>{item}</span></label>; })}</div></section>)}</div><div className="flex flex-wrap gap-3"><button className="btn btn-primary" onClick={save}>Save progress</button><button className="btn btn-secondary" onClick={() => { try { const parsed:unknown=JSON.parse(localStorage.getItem("nytm-launch-checklist")||"[]"); if (!Array.isArray(parsed)) throw Error(); setDone([...new Set(parsed.filter((v):v is string=>typeof v==="string"&&/^[0-3]-[0-3]$/.test(v)))]); setNotice("Saved progress loaded."); } catch { setNotice("Saved progress could not be read."); } }}>Load saved progress</button><button className="btn btn-secondary" onClick={() => downloadText(checks.map(([group,...items],g)=>group+"\n"+items.map((item,i)=>`[${done.includes(`${g}-${i}`)?"x":" "}] ${item}`).join("\n")).join("\n\n"),"website-launch-checklist.txt")}>Export checklist</button><button className="btn btn-secondary" onClick={() => { setDone([]); try { localStorage.removeItem("nytm-launch-checklist"); } catch {} setNotice("Checklist and saved progress cleared."); }}>Reset</button></div><Notice>{notice}</Notice></Workspace>;
}

export function AutomationSavings() {
  const [minutes,setMinutes]=useState(15); const [runs,setRuns]=useState(20); const [rate,setRate]=useState(500); const [saving,setSaving]=useState(70); const [setup,setSetup]=useState(20000); const [monthly,setMonthly]=useState(0); const [currency,setCurrency]=useState("INR");
  const hours=minutes*runs*52/12/60*saving/100; const gross=hours*rate; const net=gross-monthly;
  const result=`Estimated hours saved / month: ${hours.toFixed(1)}\nValue of time saved / month: ${currency} ${gross.toFixed(2)}\nRecurring cost / month: ${currency} ${monthly.toFixed(2)}\nNet monthly value: ${currency} ${net.toFixed(2)}\nFirst-year value after setup: ${currency} ${(net*12-setup).toFixed(2)}\nSetup payback: ${net>0 ? (setup/net).toFixed(1)+" months" : "No payback under these assumptions"}`;
  return <Workspace slug="automation-savings" help="Uses 52 weeks ÷ 12 months. Time saved is an estimate, not guaranteed cash savings. Include ongoing software and maintenance costs, and validate the assumptions with your team."><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5"><Field label="Minutes per task" type="number" min={0} value={minutes} onChange={v=>setMinutes(Math.max(0,Number(v)))} /><Field label="Tasks per week" type="number" min={0} value={runs} onChange={v=>setRuns(Math.max(0,Number(v)))} /><Field label="Hourly cost" type="number" min={0} value={rate} onChange={v=>setRate(Math.max(0,Number(v)))} /><Field label="Time saved (%)" type="number" min={0} max={100} value={saving} onChange={v=>setSaving(Math.max(0,Math.min(100,Number(v))))} /><Field label="One-time setup cost" type="number" min={0} value={setup} onChange={v=>setSetup(Math.max(0,Number(v)))} /><Field label="Monthly running cost" type="number" min={0} value={monthly} onChange={v=>setMonthly(Math.max(0,Number(v)))} /><Choice label="Currency" value={currency} onChange={setCurrency} options={[["INR","INR"],["USD","USD"],["EUR","EUR"],["GBP","GBP"]]} /></div><Result text={result} filename="automation-estimate.txt" label="Your estimate" /></Workspace>;
}
