// Printable quotations with line items and totals | TypeScript
"use client";
import { useState } from "react";
import { Workspace, Field, Choice, Notice } from "./ToolUI";
import { escapeHtml as h, printDocument, printableDocument, downloadText } from "@/lib/browser-files";

interface Item { id: number; description: string; quantity: number; rate: number }
export default function QuotationMaker() {
  const [business,setBusiness]=useState(""); const [client,setClient]=useState(""); const [number,setNumber]=useState("EST-001"); const [date,setDate]=useState(""); const [validUntil,setValidUntil]=useState(""); const [currency,setCurrency]=useState("INR"); const [discount,setDiscount]=useState(0); const [tax,setTax]=useState(0); const [notes,setNotes]=useState("Prices and scope are subject to confirmation."); const [items,setItems]=useState<Item[]>([{id:1,description:"",quantity:1,rate:0}]); const [notice,setNotice]=useState("");
  const subtotal=items.reduce((n,i)=>n+i.quantity*i.rate,0); const discounted=subtotal*(1-discount/100); const taxAmount=discounted*tax/100; const total=discounted+taxAmount;
  const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency}).format(n);
  const update=(id:number,patch:Partial<Item>)=>setItems(items.map(i=>i.id===id?{...i,...patch}:i));
  const valid=!!business.trim()&&!!client.trim()&&items.every(i=>i.description.trim()&&i.quantity>0&&i.rate>=0)&&Number.isFinite(total)&&(!date||!validUntil||date<=validUntil);
  const body=`<h1>${h(business)}</h1><h2>Quotation ${h(number)}</h2><p>Prepared for: ${h(client)}\nDate: ${h(date||"Not specified")}\nValid until: ${h(validUntil||"Not specified")}</p><table><thead><tr><th>Description</th><th>Quantity</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${items.map(i=>`<tr><td>${h(i.description)}</td><td>${i.quantity}</td><td>${h(money(i.rate))}</td><td>${h(money(i.quantity*i.rate))}</td></tr>`).join("")}</tbody></table><p>Subtotal: ${h(money(subtotal))}\nDiscount (${discount}%): ${h(money(subtotal-discounted))}\nTax (${tax}%): ${h(money(taxAmount))}</p><h2>Total: ${h(money(total))}</h2><p>${h(notes)}</p>`;
  return <Workspace slug="quotation-maker" help="This creates an estimate, not a tax-compliant invoice. Tax is a single user-entered percentage applied after the discount. Print / Save PDF opens your browser's print dialog; choose Save as PDF. No automatic tax rates are assumed."><div className="grid sm:grid-cols-2 gap-5"><Field label="Your business (required)" value={business} onChange={setBusiness} /><Field label="Prepared for (required)" value={client} onChange={setClient} /><Field label="Quotation number" value={number} onChange={setNumber} /><Choice label="Currency" value={currency} onChange={setCurrency} options={[["INR","Indian rupee"],["USD","US dollar"],["EUR","Euro"],["GBP","British pound"]]} /><Field label="Date" type="date" value={date} onChange={setDate} /><Field label="Valid until" type="date" value={validUntil} onChange={setValidUntil} /></div>
    <section><h2 className="text-xl font-semibold mb-4">Line items</h2><div className="space-y-4">{items.map((item,index)=><div key={item.id} className="grid sm:grid-cols-[2fr_1fr_1fr_auto] items-end gap-3 border-b border-[var(--border)] pb-4"><Field label={`Item ${index+1}`} value={item.description} onChange={v=>update(item.id,{description:v})} /><Field label="Quantity" type="number" min={0.01} step={0.01} value={item.quantity} onChange={v=>update(item.id,{quantity:Math.max(0,Number(v))})} /><Field label="Unit rate" type="number" min={0} step={0.01} value={item.rate} onChange={v=>update(item.id,{rate:Math.max(0,Number(v))})} /><button className="btn btn-secondary" aria-label={`Remove item ${index+1}`} disabled={items.length===1} onClick={()=>setItems(items.filter(i=>i.id!==item.id))}>Remove</button></div>)}</div><button className="btn btn-secondary mt-4" disabled={items.length>=100} onClick={()=>setItems([...items,{id:Math.max(...items.map(i=>i.id))+1,description:"",quantity:1,rate:0}])}>Add item</button></section>
    <div className="grid sm:grid-cols-2 gap-5"><Field label="Discount (%)" type="number" min={0} max={100} value={discount} onChange={v=>setDiscount(Math.min(100,Math.max(0,Number(v))))} /><Field label="Tax (%)" type="number" min={0} max={100} value={tax} onChange={v=>setTax(Math.min(100,Math.max(0,Number(v))))} /></div><Field label="Notes and terms" multiline value={notes} onChange={setNotes} /><div className="border-y border-[var(--border)] py-5 space-y-2"><p>Subtotal: {money(subtotal)}</p><p>Discount: {money(subtotal-discounted)}</p><p>Tax: {money(taxAmount)}</p><p className="text-2xl font-semibold">Total: {money(total)}</p></div><div className="flex flex-wrap gap-3"><button className="btn btn-primary" disabled={!valid} onClick={()=>{try {printDocument(`Quotation ${number}`,body);setNotice("");}catch(e){setNotice((e as Error).message);}}}>Print / Save PDF</button><button className="btn btn-secondary" disabled={!valid} onClick={()=>downloadText(printableDocument(`Quotation ${number}`,body),"quotation.html","text/html;charset=utf-8")}>Download HTML</button></div>{!valid&&<Notice>Enter business, client, and item descriptions, positive quantities, and a valid date range.</Notice>}<Notice>{notice}</Notice></Workspace>;
}
