export interface ToolConfig {
  slug: string;
  name: string;
  description: string;
  category: "text" | "image" | "dev" | "converter" | "generator" | "security" | "misc";
  icon?: string;
  inputType: "text" | "file" | "both" | "none";
  isNew?: boolean;
  keywords?: string[];
}

export const toolsConfig: ToolConfig[] = [
  // Text Tools
  {
    slug: "summary",
    name: "Text Summary",
    description: "Generate a concise summary from long text content using intelligent extraction.",
    category: "text",
    icon: "clipboard",
    inputType: "text",
    keywords: ["summarize", "tldr", "shorten"],
  },
  {
    slug: "bullet-points",
    name: "Bullet Points",
    description: "Convert paragraphs into organized bullet point lists.",
    category: "text",
    icon: "pin",
    inputType: "text",
    keywords: ["list", "points", "organize"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs in your text.",
    category: "text",
    icon: "number",
    inputType: "text",
    keywords: ["count", "words", "characters"],
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    description: "Count characters with and without spaces.",
    category: "text",
    icon: "chart-bar",
    inputType: "text",
    keywords: ["count", "characters", "length"],
  },
  {
    slug: "line-counter",
    name: "Line Counter",
    description: "Count lines and non-empty lines in your text.",
    category: "text",
    icon: "ruler",
    inputType: "text",
    keywords: ["count", "lines", "rows"],
  },
  {
    slug: "text-case",
    name: "Text Case Converter",
    description: "Convert text between uppercase, lowercase, title case, sentence case, and more.",
    category: "text",
    icon: "text-aa",
    inputType: "text",
    keywords: ["uppercase", "lowercase", "titlecase", "camelcase"],
  },
  {
    slug: "text-reverse",
    name: "Text Reverser",
    description: "Reverse text, words, or lines.",
    category: "text",
    icon: "arrow-path",
    inputType: "text",
    keywords: ["reverse", "backwards", "flip"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text.",
    category: "text",
    icon: "scroll",
    inputType: "none",
    keywords: ["placeholder", "dummy", "text"],
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    description: "Compare two texts and highlight differences.",
    category: "text",
    icon: "magnifying-glass",
    inputType: "text",
    keywords: ["compare", "difference", "diff"],
  },
  {
    slug: "remove-duplicates",
    name: "Remove Duplicates",
    description: "Remove duplicate lines from your text.",
    category: "text",
    icon: "trash",
    inputType: "text",
    keywords: ["unique", "dedupe", "duplicates"],
  },
  {
    slug: "sort-lines",
    name: "Sort Lines",
    description: "Sort lines alphabetically, numerically, or randomly.",
    category: "text",
    icon: "signal",
    inputType: "text",
    keywords: ["sort", "alphabetical", "order"],
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    description: "Find and replace text with support for regex.",
    category: "text",
    icon: "magnifying-glass",
    inputType: "text",
    keywords: ["find", "replace", "regex", "search"],
  },
  {
    slug: "text-trim",
    name: "Text Trimmer",
    description: "Trim whitespace from beginning, end, or both sides of text.",
    category: "text",
    icon: "scissors",
    inputType: "text",
    keywords: ["trim", "whitespace", "strip"],
  },
  {
    slug: "text-repeat",
    name: "Text Repeater",
    description: "Repeat text multiple times with customizable separator.",
    category: "text",
    icon: "arrow-path",
    inputType: "text",
    keywords: ["repeat", "multiply", "duplicate"],
  },
  {
    slug: "text-join",
    name: "Text Joiner",
    description: "Join multiple lines with a custom delimiter.",
    category: "text",
    icon: "link",
    inputType: "text",
    keywords: ["join", "merge", "combine"],
  },
  {
    slug: "text-split",
    name: "Text Splitter",
    description: "Split text by delimiter into multiple lines.",
    category: "text",
    icon: "scissors",
    inputType: "text",
    keywords: ["split", "separate", "divide"],
  },
  {
    slug: "add-prefix-suffix",
    name: "Add Prefix/Suffix",
    description: "Add prefix and/or suffix to each line.",
    category: "text",
    icon: "plus",
    inputType: "text",
    keywords: ["prefix", "suffix", "wrap"],
  },
  {
    slug: "number-lines",
    name: "Line Numbering",
    description: "Add line numbers to each line of text.",
    category: "text",
    icon: "number",
    inputType: "text",
    keywords: ["number", "lines", "count"],
  },
  {
    slug: "remove-empty-lines",
    name: "Remove Empty Lines",
    description: "Remove all empty or whitespace-only lines.",
    category: "text",
    icon: "broom",
    inputType: "text",
    keywords: ["empty", "blank", "clean"],
  },
  {
    slug: "text-extract",
    name: "Text Extractor",
    description: "Extract emails, URLs, numbers, or hashtags from text.",
    category: "text",
    icon: "target",
    inputType: "text",
    keywords: ["extract", "emails", "urls", "numbers"],
  },

  // Developer Tools
  {
    slug: "json-pretty",
    name: "JSON Beautifier",
    description: "Format and beautify JSON with syntax highlighting and validation.",
    category: "dev",
    icon: "paint-brush",
    inputType: "text",
    keywords: ["json", "format", "beautify", "pretty"],
  },
  {
    slug: "json-minify",
    name: "JSON Minifier",
    description: "Minify JSON by removing whitespace.",
    category: "dev",
    icon: "archive-box",
    inputType: "text",
    keywords: ["json", "minify", "compress"],
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    description: "Validate JSON syntax and display errors.",
    category: "dev",
    icon: "check-circle",
    inputType: "text",
    keywords: ["json", "validate", "check"],
  },
  {
    slug: "json-path",
    name: "JSON Path Finder",
    description: "Query JSON data using JSONPath expressions.",
    category: "dev",
    icon: "magnifying-glass",
    inputType: "text",
    keywords: ["json", "path", "query"],
  },
  {
    slug: "json-escape",
    name: "JSON Escape/Unescape",
    description: "Escape or unescape JSON strings.",
    category: "dev",
    icon: "lock",
    inputType: "text",
    keywords: ["json", "escape", "unescape"],
  },
  {
    slug: "markdown-clean",
    name: "Markdown Cleaner",
    description: "Clean and standardize markdown formatting.",
    category: "dev",
    icon: "pencil",
    inputType: "text",
    keywords: ["markdown", "clean", "format"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Preview markdown rendered as HTML.",
    category: "dev",
    icon: "eye",
    inputType: "text",
    keywords: ["markdown", "preview", "render"],
  },
  {
    slug: "html-beautify",
    name: "HTML Beautifier",
    description: "Format and indent HTML code.",
    category: "dev",
    icon: "globe",
    inputType: "text",
    keywords: ["html", "beautify", "format"],
  },
  {
    slug: "html-minify",
    name: "HTML Minifier",
    description: "Minify HTML by removing whitespace and comments.",
    category: "dev",
    icon: "archive-box",
    inputType: "text",
    keywords: ["html", "minify", "compress"],
  },
  {
    slug: "html-entities",
    name: "HTML Entities Encoder",
    description: "Encode or decode HTML entities.",
    category: "dev",
    icon: "hash",
    inputType: "text",
    keywords: ["html", "entities", "encode", "decode"],
  },
  {
    slug: "html-encode",
    name: "HTML Encoder",
    description: "Encode special characters to HTML entities.",
    category: "dev",
    icon: "lock",
    inputType: "text",
    keywords: ["html", "encode", "entities"],
  },
  {
    slug: "html-decode",
    name: "HTML Decoder",
    description: "Decode HTML entities back to characters.",
    category: "dev",
    icon: "unlock",
    inputType: "text",
    keywords: ["html", "decode", "entities"],
  },
  {
    slug: "html-strip",
    name: "HTML Tag Stripper",
    description: "Remove all HTML tags from text.",
    category: "dev",
    icon: "broom",
    inputType: "text",
    keywords: ["html", "strip", "remove", "tags"],
  },
  {
    slug: "css-beautify",
    name: "CSS Beautifier",
    description: "Format and beautify CSS code.",
    category: "dev",
    icon: "paint-brush",
    inputType: "text",
    keywords: ["css", "beautify", "format"],
  },
  {
    slug: "css-minify",
    name: "CSS Minifier",
    description: "Minify CSS by removing whitespace and comments.",
    category: "dev",
    icon: "archive-box",
    inputType: "text",
    keywords: ["css", "minify", "compress"],
  },
  {
    slug: "js-beautify",
    name: "JavaScript Beautifier",
    description: "Format and beautify JavaScript code.",
    category: "dev",
    icon: "sparkles",
    inputType: "text",
    keywords: ["javascript", "js", "beautify", "format"],
  },
  {
    slug: "js-minify",
    name: "JavaScript Minifier",
    description: "Minify JavaScript code.",
    category: "dev",
    icon: "archive-box",
    inputType: "text",
    keywords: ["javascript", "js", "minify", "compress"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries.",
    category: "dev",
    icon: "database",
    inputType: "text",
    keywords: ["sql", "format", "beautify"],
  },
  {
    slug: "xml-beautify",
    name: "XML Beautifier",
    description: "Format and beautify XML code.",
    category: "dev",
    icon: "document",
    inputType: "text",
    keywords: ["xml", "beautify", "format"],
  },
  {
    slug: "xml-minify",
    name: "XML Minifier",
    description: "Minify XML by removing whitespace.",
    category: "dev",
    icon: "archive-box",
    inputType: "text",
    keywords: ["xml", "minify", "compress"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug regular expressions with highlighting.",
    category: "dev",
    icon: "wrench",
    inputType: "text",
    keywords: ["regex", "regular expression", "test"],
  },
  {
    slug: "base64-encode",
    name: "Base64 Encoder",
    description: "Encode text to Base64 format.",
    category: "dev",
    icon: "lock",
    inputType: "text",
    keywords: ["base64", "encode"],
  },
  {
    slug: "base64-decode",
    name: "Base64 Decoder",
    description: "Decode Base64 to plain text.",
    category: "dev",
    icon: "unlock",
    inputType: "text",
    keywords: ["base64", "decode"],
  },
  {
    slug: "url-encode",
    name: "URL Encoder",
    description: "Encode text for use in URLs.",
    category: "dev",
    icon: "link",
    inputType: "text",
    keywords: ["url", "encode", "percent"],
  },
  {
    slug: "url-decode",
    name: "URL Decoder",
    description: "Decode URL-encoded text.",
    category: "dev",
    icon: "link",
    inputType: "text",
    keywords: ["url", "decode", "percent"],
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Parse and analyze URL components.",
    category: "dev",
    icon: "globe",
    inputType: "text",
    keywords: ["url", "parse", "analyze"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens.",
    category: "dev",
    icon: "ticket",
    inputType: "text",
    keywords: ["jwt", "token", "decode"],
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Generate JWT tokens with custom payload.",
    category: "dev",
    icon: "ticket",
    inputType: "text",
    keywords: ["jwt", "token", "generate"],
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse and validate cron expressions.",
    category: "dev",
    icon: "clock",
    inputType: "text",
    keywords: ["cron", "schedule", "parser"],
  },
  {
    slug: "code-to-image",
    name: "Code to Image",
    description: "Convert code snippets to beautiful images.",
    category: "dev",
    icon: "camera",
    inputType: "text",
    keywords: ["code", "image", "screenshot"],
    isNew: true,
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two pieces of text and show differences.",
    category: "dev",
    icon: "arrows-right-left",
    inputType: "text",
    keywords: ["diff", "compare", "code"],
  },
  {
    slug: "code-minifier",
    name: "Code Minifier",
    description: "Minify JavaScript, CSS, HTML, and JSON code.",
    category: "dev",
    icon: "archive-box",
    inputType: "text",
    keywords: ["minify", "compress", "code"],
  },
  {
    slug: "escape-unescape",
    name: "String Escape/Unescape",
    description: "Escape or unescape strings for various languages.",
    category: "dev",
    icon: "lock",
    inputType: "text",
    keywords: ["escape", "unescape", "string"],
  },

  // Image Tools
  {
    slug: "beautify-screenshot",
    name: "Screenshot Beautifier",
    description: "Add beautiful backgrounds, shadows, and frames to screenshots.",
    category: "image",
    icon: "photo",
    inputType: "file",
    keywords: ["screenshot", "beautify", "mockup"],
  },
  {
    slug: "remove-bg",
    name: "Remove Background",
    description: "Remove image backgrounds automatically. Client-side processing, no uploads.",
    category: "image",
    icon: "scissors",
    inputType: "file",
    keywords: ["remove", "background", "transparent", "cutout", "erase"],
    isNew: true,
  },
  {
    slug: "image-resize",
    name: "Image Resizer",
    description: "Resize images to specific dimensions.",
    category: "image",
    icon: "arrows-pointing-out",
    inputType: "file",
    keywords: ["resize", "scale", "dimensions"],
  },
  {
    slug: "image-compress",
    name: "Image Compressor",
    description: "Compress images to reduce file size.",
    category: "image",
    icon: "archive-box",
    inputType: "file",
    keywords: ["compress", "optimize", "reduce"],
  },
  {
    slug: "image-crop",
    name: "Image Cropper",
    description: "Crop images to specific areas.",
    category: "image",
    icon: "scissors",
    inputType: "file",
    keywords: ["crop", "cut", "trim"],
  },
  {
    slug: "image-rotate",
    name: "Image Rotator",
    description: "Rotate images by any angle.",
    category: "image",
    icon: "arrow-path",
    inputType: "file",
    keywords: ["rotate", "turn", "angle"],
  },
  {
    slug: "image-flip",
    name: "Image Flipper",
    description: "Flip images horizontally or vertically.",
    category: "image",
    icon: "arrows-right-left",
    inputType: "file",
    keywords: ["flip", "mirror", "horizontal", "vertical"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 encoded strings.",
    category: "image",
    icon: "hash",
    inputType: "file",
    keywords: ["image", "base64", "encode"],
  },
  {
    slug: "base64-to-image",
    name: "Base64 to Image",
    description: "Convert Base64 strings back to images.",
    category: "image",
    icon: "photo",
    inputType: "text",
    keywords: ["base64", "image", "decode"],
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    description: "Pick colors from images or choose from palette.",
    category: "image",
    icon: "color-swatch",
    inputType: "both",
    keywords: ["color", "picker", "hex", "rgb"],
  },
  {
    slug: "palette-generator",
    name: "Palette Generator",
    description: "Generate color palettes from images.",
    category: "image",
    icon: "rainbow",
    inputType: "file",
    keywords: ["palette", "colors", "extract"],
  },
  {
    slug: "image-filters",
    name: "Image Filters",
    description: "Apply filters like grayscale, sepia, blur to images.",
    category: "image",
    icon: "masks-theater",
    inputType: "file",
    keywords: ["filter", "effects", "grayscale"],
  },
  {
    slug: "image-convert",
    name: "Image Format Converter",
    description: "Convert images between PNG, JPG, WebP, and more.",
    category: "image",
    icon: "arrow-path",
    inputType: "file",
    keywords: ["convert", "format", "png", "jpg"],
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG files to PNG images.",
    category: "image",
    icon: "arrow-path",
    inputType: "file",
    keywords: ["svg", "png", "convert"],
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicons in multiple sizes.",
    category: "image",
    icon: "star",
    inputType: "file",
    keywords: ["favicon", "icon", "generate"],
  },
  {
    slug: "placeholder-image",
    name: "Placeholder Image",
    description: "Generate placeholder images with custom dimensions.",
    category: "image",
    icon: "photo",
    inputType: "none",
    keywords: ["placeholder", "dummy", "image"],
  },

  // Converters
  {
    slug: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON data to CSV format.",
    category: "converter",
    icon: "chart-bar",
    inputType: "text",
    keywords: ["json", "csv", "convert"],
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON format.",
    category: "converter",
    icon: "chart-bar",
    inputType: "text",
    keywords: ["csv", "json", "convert"],
  },
  {
    slug: "json-to-yaml",
    name: "JSON to YAML",
    description: "Convert JSON to YAML format.",
    category: "converter",
    icon: "document",
    inputType: "text",
    keywords: ["json", "yaml", "convert"],
  },
  {
    slug: "yaml-to-json",
    name: "YAML to JSON",
    description: "Convert YAML to JSON format.",
    category: "converter",
    icon: "document",
    inputType: "text",
    keywords: ["yaml", "json", "convert"],
  },
  {
    slug: "json-to-xml",
    name: "JSON to XML",
    description: "Convert JSON to XML format.",
    category: "converter",
    icon: "document",
    inputType: "text",
    keywords: ["json", "xml", "convert"],
  },
  {
    slug: "xml-to-json",
    name: "XML to JSON",
    description: "Convert XML to JSON format.",
    category: "converter",
    icon: "document",
    inputType: "text",
    keywords: ["xml", "json", "convert"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to HTML.",
    category: "converter",
    icon: "pencil",
    inputType: "text",
    keywords: ["markdown", "html", "convert"],
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown.",
    category: "converter",
    icon: "pencil",
    inputType: "text",
    keywords: ["html", "markdown", "convert"],
  },
  {
    slug: "number-base",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hex.",
    category: "converter",
    icon: "number",
    inputType: "text",
    keywords: ["binary", "hex", "octal", "decimal"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between different units of measurement.",
    category: "converter",
    icon: "ruler",
    inputType: "text",
    keywords: ["unit", "convert", "length", "weight"],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    category: "converter",
    icon: "clock",
    inputType: "text",
    keywords: ["timestamp", "unix", "date", "time"],
  },
  {
    slug: "epoch-converter",
    name: "Epoch Converter",
    description: "Convert epoch/Unix time to readable date and vice versa.",
    category: "converter",
    icon: "calendar",
    inputType: "text",
    keywords: ["epoch", "unix", "timestamp"],
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, and more.",
    category: "converter",
    icon: "color-swatch",
    inputType: "text",
    keywords: ["color", "hex", "rgb", "hsl"],
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary",
    description: "Convert text to binary representation.",
    category: "converter",
    icon: "code",
    inputType: "text",
    keywords: ["text", "binary", "convert"],
  },
  {
    slug: "binary-to-text",
    name: "Binary to Text",
    description: "Convert binary to readable text.",
    category: "converter",
    icon: "code",
    inputType: "text",
    keywords: ["binary", "text", "convert"],
  },
  {
    slug: "text-to-hex",
    name: "Text to Hex",
    description: "Convert text to hexadecimal representation.",
    category: "converter",
    icon: "code",
    inputType: "text",
    keywords: ["text", "hex", "hexadecimal"],
  },
  {
    slug: "hex-to-text",
    name: "Hex to Text",
    description: "Convert hexadecimal to readable text.",
    category: "converter",
    icon: "code",
    inputType: "text",
    keywords: ["hex", "text", "hexadecimal"],
  },
  {
    slug: "ascii-table",
    name: "ASCII Table",
    description: "View and convert ASCII characters.",
    category: "converter",
    icon: "clipboard",
    inputType: "none",
    keywords: ["ascii", "table", "characters"],
  },
  {
    slug: "unicode-converter",
    name: "Unicode Converter",
    description: "Convert text to/from Unicode escape sequences.",
    category: "converter",
    icon: "text-aa",
    inputType: "text",
    keywords: ["unicode", "escape", "convert"],
  },

  // Generators
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v1, v4).",
    category: "generator",
    icon: "dice",
    inputType: "none",
    keywords: ["uuid", "guid", "random"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords.",
    category: "generator",
    icon: "lock",
    inputType: "none",
    keywords: ["password", "secure", "random"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate hashes using MD5, SHA1, SHA256, SHA512.",
    category: "generator",
    icon: "hash",
    inputType: "text",
    keywords: ["hash", "md5", "sha"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs.",
    category: "generator",
    icon: "qr-code",
    inputType: "text",
    keywords: ["qr", "code", "barcode"],
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate various barcode formats.",
    category: "generator",
    icon: "chart-bar",
    inputType: "text",
    keywords: ["barcode", "ean", "upc"],
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Generate URL-friendly slugs from text.",
    category: "generator",
    icon: "link",
    inputType: "text",
    keywords: ["slug", "url", "seo"],
  },
  {
    slug: "random-number",
    name: "Random Number Generator",
    description: "Generate random numbers within a range.",
    category: "generator",
    icon: "slot-machine",
    inputType: "none",
    keywords: ["random", "number", "range"],
  },
  {
    slug: "random-string",
    name: "Random String Generator",
    description: "Generate random alphanumeric strings.",
    category: "generator",
    icon: "text-aa",
    inputType: "none",
    keywords: ["random", "string", "alphanumeric"],
  },
  {
    slug: "fake-data",
    name: "Fake Data Generator",
    description: "Generate fake names, emails, addresses, and more.",
    category: "generator",
    icon: "user-circle",
    inputType: "none",
    keywords: ["fake", "mock", "data", "name", "email"],
  },
  {
    slug: "credit-card-generator",
    name: "Test Credit Card Generator",
    description: "Generate valid test credit card numbers for development.",
    category: "generator",
    icon: "credit-card",
    inputType: "none",
    keywords: ["credit card", "test", "development"],
  },
  {
    slug: "ip-generator",
    name: "Random IP Generator",
    description: "Generate random IPv4 or IPv6 addresses.",
    category: "generator",
    icon: "globe",
    inputType: "none",
    keywords: ["ip", "ipv4", "ipv6", "random"],
  },
  {
    slug: "mac-address-generator",
    name: "MAC Address Generator",
    description: "Generate random MAC addresses.",
    category: "generator",
    icon: "signal-wifi",
    inputType: "none",
    keywords: ["mac", "address", "network"],
  },
  {
    slug: "iban-generator",
    name: "IBAN Generator",
    description: "Generate valid IBAN numbers for testing.",
    category: "generator",
    icon: "building-library",
    inputType: "none",
    keywords: ["iban", "bank", "test"],
  },

  // Security Tools
  {
    slug: "md5-hash",
    name: "MD5 Hash Generator",
    description: "Generate MD5 hash from text.",
    category: "security",
    icon: "hash",
    inputType: "text",
    keywords: ["md5", "hash", "checksum"],
  },
  {
    slug: "sha1-hash",
    name: "SHA1 Hash Generator",
    description: "Generate SHA1 hash from text.",
    category: "security",
    icon: "hash",
    inputType: "text",
    keywords: ["sha1", "hash", "checksum"],
  },
  {
    slug: "sha256-hash",
    name: "SHA256 Hash Generator",
    description: "Generate SHA256 hash from text.",
    category: "security",
    icon: "hash",
    inputType: "text",
    keywords: ["sha256", "hash", "checksum"],
  },
  {
    slug: "sha512-hash",
    name: "SHA512 Hash Generator",
    description: "Generate SHA512 hash from text.",
    category: "security",
    icon: "hash",
    inputType: "text",
    keywords: ["sha512", "hash", "checksum"],
  },
  {
    slug: "bcrypt-hash",
    name: "Bcrypt Hash Generator",
    description: "Generate bcrypt hashes for passwords.",
    category: "security",
    icon: "lock",
    inputType: "text",
    keywords: ["bcrypt", "hash", "password"],
  },
  {
    slug: "bcrypt-verify",
    name: "Bcrypt Verifier",
    description: "Verify bcrypt hashes.",
    category: "security",
    icon: "check-circle",
    inputType: "text",
    keywords: ["bcrypt", "verify", "password"],
  },
  {
    slug: "aes-encrypt",
    name: "AES Encrypt",
    description: "Encrypt text using AES encryption.",
    category: "security",
    icon: "lock",
    inputType: "text",
    keywords: ["aes", "encrypt", "cipher"],
  },
  {
    slug: "aes-decrypt",
    name: "AES Decrypt",
    description: "Decrypt AES encrypted text.",
    category: "security",
    icon: "unlock",
    inputType: "text",
    keywords: ["aes", "decrypt", "cipher"],
  },
  {
    slug: "rsa-key-generator",
    name: "RSA Key Generator",
    description: "Generate RSA public/private key pairs.",
    category: "security",
    icon: "key",
    inputType: "none",
    keywords: ["rsa", "key", "public", "private"],
  },
  {
    slug: "password-strength",
    name: "Password Strength Checker",
    description: "Check the strength of your passwords.",
    category: "security",
    icon: "muscle",
    inputType: "text",
    keywords: ["password", "strength", "security"],
  },
  {
    slug: "hash-identifier",
    name: "Hash Identifier",
    description: "Identify the type of hash.",
    category: "security",
    icon: "magnifying-glass",
    inputType: "text",
    keywords: ["hash", "identify", "type"],
  },
  {
    slug: "file-hash",
    name: "File Hash Calculator",
    description: "Calculate hash of uploaded files.",
    category: "security",
    icon: "folder",
    inputType: "file",
    keywords: ["file", "hash", "checksum"],
  },

  // Misc Tools
  {
    slug: "ip-lookup",
    name: "IP Lookup",
    description: "Get your public IP and location info.",
    category: "misc",
    icon: "globe",
    inputType: "none",
    keywords: ["ip", "lookup", "location"],
  },
  {
    slug: "user-agent-parser",
    name: "User Agent Parser",
    description: "Parse and analyze user agent strings.",
    category: "misc",
    icon: "device-phone-mobile",
    inputType: "text",
    keywords: ["user agent", "browser", "parse"],
  },
  {
    slug: "http-headers",
    name: "HTTP Headers Viewer",
    description: "View HTTP headers for any URL.",
    category: "misc",
    icon: "clipboard",
    inputType: "text",
    keywords: ["http", "headers", "request"],
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios and dimensions.",
    category: "misc",
    icon: "calculator",
    inputType: "text",
    keywords: ["aspect", "ratio", "dimensions"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages and percentage differences.",
    category: "misc",
    icon: "calculator",
    inputType: "text",
    keywords: ["percentage", "calculate", "percent"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate age from birth date.",
    category: "misc",
    icon: "cake",
    inputType: "text",
    keywords: ["age", "birthday", "calculate"],
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    description: "Calculate date differences and add/subtract days.",
    category: "misc",
    icon: "calendar",
    inputType: "text",
    keywords: ["date", "difference", "calculate"],
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Create countdowns to specific dates.",
    category: "misc",
    icon: "clock",
    inputType: "none",
    keywords: ["countdown", "timer", "date"],
  },
  {
    slug: "stopwatch",
    name: "Stopwatch",
    description: "Simple online stopwatch with lap times.",
    category: "misc",
    icon: "clock",
    inputType: "none",
    keywords: ["stopwatch", "timer", "time"],
  },
  {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Productivity timer using Pomodoro technique.",
    category: "misc",
    icon: "tomato",
    inputType: "none",
    keywords: ["pomodoro", "productivity", "timer"],
  },
  {
    slug: "world-clock",
    name: "World Clock",
    description: "View time in different time zones.",
    category: "misc",
    icon: "globe-americas",
    inputType: "none",
    keywords: ["time", "timezone", "world"],
  },
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert time between different timezones.",
    category: "misc",
    icon: "clock",
    inputType: "none",
    keywords: ["time", "timezone", "convert"],
  },
  {
    slug: "emoji-picker",
    name: "Emoji Picker",
    description: "Search and copy emojis easily.",
    category: "misc",
    icon: "smile-face",
    inputType: "none",
    keywords: ["emoji", "emoticon", "copy"],
  },
  {
    slug: "keyboard-tester",
    name: "Keyboard Tester",
    description: "Test your keyboard keys.",
    category: "misc",
    icon: "keyboard",
    inputType: "none",
    keywords: ["keyboard", "test", "keys"],
  },
  {
    slug: "screen-resolution",
    name: "Screen Resolution",
    description: "Check your screen resolution and device info.",
    category: "misc",
    icon: "computer-desktop",
    inputType: "none",
    keywords: ["screen", "resolution", "display"],
  },
  {
    slug: "morse-code",
    name: "Morse Code Translator",
    description: "Translate text to/from Morse code.",
    category: "misc",
    icon: "radio",
    inputType: "text",
    keywords: ["morse", "code", "translate"],
  },
  {
    slug: "nato-alphabet",
    name: "NATO Alphabet Converter",
    description: "Convert text to NATO phonetic alphabet.",
    category: "misc",
    icon: "text-aa",
    inputType: "text",
    keywords: ["nato", "phonetic", "alphabet"],
  },
  {
    slug: "roman-numerals",
    name: "Roman Numeral Converter",
    description: "Convert between Arabic and Roman numerals.",
    category: "misc",
    icon: "number",
    inputType: "text",
    keywords: ["roman", "numeral", "convert"],
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index.",
    category: "misc",
    icon: "scale",
    inputType: "text",
    keywords: ["bmi", "health", "weight"],
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tips and split bills.",
    category: "misc",
    icon: "banknotes",
    inputType: "text",
    keywords: ["tip", "bill", "calculate"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate loan payments and interest.",
    category: "misc",
    icon: "building-library",
    inputType: "text",
    keywords: ["loan", "interest", "payment"],
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return toolsConfig.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolConfig["category"]): ToolConfig[] {
  return toolsConfig.filter((tool) => tool.category === category);
}

export function searchTools(query: string): ToolConfig[] {
  const lowerQuery = query.toLowerCase();
  return toolsConfig.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.keywords?.some((k) => k.toLowerCase().includes(lowerQuery))
  );
}
